### ISSUE TITLE
Improve text2rest

### ISSUE THREAD

**Issue by m2rtk** [WaldurChatbot/Waldur-Chatbot#23] opened 2017-10-15 19:50 UTC
At the moment we just check if request contains certain words. Ex. if 'my' and 'projects' are in request string, we query user projects from Waldur API.

**Comment by kyttike** [comment] 2017-10-15 22:31
Chatterbot's documentation will probably be helpful here.

Maybe identifying key-words is the way to go, as they would be processed by different adapters and trigger different api calls. 

Will there be a situation where same keywords can trigger different api calls depending on context?

**Comment by SilverKiro** [comment] 2017-10-24 19:38
Associated [functional requirement](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Functional-requirements): 1

**Comment by aleemet** [comment] 2017-11-12 22:59
duplicate of #29

**Closed as completed by aleemet** 2017-11-12 22:59 UTC
Labels: enhancement
